[package]
name = "async_queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { version = "0.8.0", features = ["user-operations", "derive"] }
memoffset = "0.9.1"
ctrlc = "3.4.4"
